rubenv/sql-migrate

migrate.go, migrate_test.go
If there are migrations missing before the last run migration, for
example because of a merge, migrate up to the latest run migration
first before applying the user-requested migrations.
Example: if the existing migrations in the database are:
- 1
- 3
and the existing migrations on disk are:
- 1
- 2
- 3
- 4
- 5
For "up, n=0" (3=>5) one would expect these migrations to run:
- up 2
- up 4
- up 5
For "up, n=1" (3=>4) one would expect:
- up 2
- up 4
For "down, n=1" (3=>2) one would expect:
- up 2
- down 3
- down 2
etc.
We had this problem in production, and this patch solved it for us.
=> Account for "holes" in the existing migrations in PlanMigration

migrate.go
This PR will improve the clarity of transaction-related errors by associating messages with a particular migration id.  No additional tests have been added at this time.
For example, this:
ERROR: syntax error at or near "blah" (SQLSTATE 42601)
will now produce:
ERROR: syntax error at or near "blah" (SQLSTATE 42601) handling 0000_some_filename.sql
go test passes, but I will need direction from @rubenv regarding whether or not additional testing is desirable and, if so, what is the preference for the design/approach of such testing.
=> Add custom TxError to add clarity to tx-related error messages.

migrate.go, migrate_test.go
Currently, the two following migrations are considered to have the same version:
```
20160126_1100_migration1.sql
20160126_1200_migration2.sql
```
This happens because only the first number in the ID string is used for comparion, i.e. `20160126` for both migrations. The patch fixes this by falling back to string comparsion when `Migration.VersionInt()` returns the same version for two migrations.
Also, generalize temporary filename used for `migration_test.go` by using `ioutil.TempFile()` to create one.
=> Support timestamp 'versions' by falling back to string comparison when to VersionInts() are equal

sql-migrate/config.go, test-integration/dbconfig.yml, test-integration/mysql-env.sh
Environment variable expansion let's you define all or parts of the datasource individually for each user without changing the config.
To use this feature, put `$VARIABLE` or `${VARIABLE}` as placeholder in the datasource string.
=> Expand environment variables in datasource

migrate.go, sqlparse/sqlparse.go, sqlparse/sqlparse_test.go
This PR fixes #13 by:
1. Refactoring the parser to allow sql-migrate commands to take options
2. Adds a "notransaction" option to the "Up" and "Down" commands as suggested in #13 
3. Honors the "notransaction" option by using the raw `DbMap` for database calls instead of creating a transaction
=> Support notransaction mode

migrate.go, migrate_test.go
Previously the table name wasn't being quoted (for example when the table name was `migrations-web`) and resulted in the error:
```
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax
to use near '-web' at line 1
```
This uses gorp's functions to correctly handle schemaName (if set) and tableName for the dialects of SQL it supports.
=> Quote tableName when querying migrations

README.md, sqlparse/sqlparse.go, sqlparse/sqlparse_test.go
This PR adds the ability to specify a string that, if matched, will split up a list of migrations. This suits our workflow on MS SQL projects, where semicolons are optional and statements are separated by a line containing only the word `GO`, as in MS SQL Query Analyzer.
This PR also includes the line terminator bug fix from https://github.com/rubenv/sql-migrate/pull/53
=> Allow custom line terminator

sql-migrate/command_new.go
Currently, `sql-migrate new -env="foo" name` will pick `-env="foo"` as the name. This changes it to use the first argument that isn't a flag rather than simply the first argument.
=> Create a migration from the first non-flag arg

README.md, sqlparse/LICENSE, sqlparse/README.md
Moved the licenses out of the README's, there's no need for them there.
=> Link to licenses

sql-migrate/command_new.go
Change time.Now().Format("20060201150405") to time.Now().Format("20060102150405")
Because golang decides the order of date format.
1 = month
2 = day
FYI: https://golang.org/src/time/format.go
ref. #65
=> Refactor time.Now().Format("20060201150405")

migrate.go, migrate_test.go
I would like to be able to use an `http.FileSystem` (the closest to a virtual filesystem interface standard library has) as a migration source.
The use case is that I use an embedding tool that uses this http.FileSystem as interface.
=> Add HttpFileSystemSource support.

sqlparse/sqlparse.go, sqlparse/sqlparse_test.go
In previous version of sql-migrate, it was ok to write "-- +migrate Down" with just a comment.
Now, on master, it's not possible anymore.
This PR will allow user to comment a  section without having a sql instruction.
The comments are also ignored properly.
Example:
"
-- +migrate Down
-- no migration here
"
=> feat: allow only comment

migrate.go
This can happen if multiple processes are trying to concurrently run the same migrations.
=> Don't leak transactions if there is a failure writing to the migrations table.

sql-migrate/command_status.go
When a migration file is removed, command `sql-migrate status` will panic as it couldn't find the relevant file on migration folder. This PR attempts to fix that panic.
=> Fix panic when migration file removed

migrate.go
Concurrent usage of the `MemoryMigrationSource` was impossible because
it was mutating its `Migrations` property in place. This commit makes
this possible by making sure the `FindMigrations` sorts a copy of the
migrations list instead of the shared one.
=> Fix a race condition in the sql-migrate memory migration struct

migrate.go, migrate_test.go, sql-migrate/command_skip.go, sql-migrate/main.go
Add support for a "skip" command which will process all .sql migration files as no-operations, but still write the schema table version with the last found version.
This provides a way to apply sql-migrate versioning to pre-existing databases where you don't necessarily want to run from the initial schema file, but from some later point.
Supports all the same flags and options as the Up command.
=> Add skip command to support versioning pre-existing db's

README.md
For users not used to `go get` it can look like it is stuck because nothing is printed on the screen for sometime, adding the `-v` display some progress.
=> Adds verbose(`-v`) flag to install command line

migrate.go, migrate_test.go
As discussed in #43 and #85 there are problems when the database contains migrations which are not part of the current plan. Up to this PR `sql-migrate` was just ignoring such cases and hoped for the best.
The PR adds a new error type `PlanError` and uses it when a mismatch between the database migrations and the current source migrations is found. This way one would be able to ignore this error while using `sql-migrate` as a library if need be.
=> PlanMigration returns error when no safe migration is possible

README.md
fixes #107 
The current readme is using both dbconfig.yml and config.yml.
This makes the user unsure about what is best practice naming the config file.
=> Fix inconsistent naming of config files #107

sql-migrate/command_skip.go
Fixed an issue where skip messages were not displayed correctly.
before fixing
```
// n = 0
$ ./sql-migrate skip
Skipped 1 migration
Skipped 0 migrations
// n = 1
$ ./sql-migrate skip
Skipped 1 migration
Skipped 1 migration
// n > 2
$ ./sql-migrate skip
Skipped 1 migration
Skipped n migrations
```
after fixing
```
// n = 0
$ ./sql-migrate skip
All migrations have already been applied
// n = 1
$ ./sql-migrate skip
Skipped 1 migrations
// n > 2
$ ./sql-migrate skip
Skipped n migrations
```
=> fix skip message

sql-migrate/command_redo.go
When you want to reapply a migration and there is an error, sql-migrate shows:
`Nothing to do!`
Which is not true in the case of having errors. Now, in order to know which error do you have, you need to perform sql-migrate down and then up again.
The proposal is to print the error and exit the program
=> Print error message on redo command

README.md, migrate_test.go
=> Use packr v2 on examples and tests

migrate.go, migrate_test.go
Usage of global variable in migrate package make difficult the concurrent usage of sql-migrate on two (or more) databases/schema.
This PR introduce a MigrationSet type that provide a way to instanciate sql-migrate with different parameters for databases.
To ensure backward compatibility the global variables (tableName and schemaName) are replaced by a MigrationSet instance and functions without receiver call their MigrationSet counterpart on this instance).
=> Add type MigrationSet to allow concurrent usage of sql-migrate

migrate.go, migrate_test.go
I know this seems like a very strange request. But as it isn't a backwards breaking and I may not be the only one, I figure why not open a PR.
Scenario:
In a microservice type situation where each service maintains its own schema (yes only schema, not DB), there is a case where this pops up.
In Postgres, I have a `public` schema in each DB and a `service_name` schema that is owned by a particular service. Multiple services can share the same DB. That way a service can read (not write) to other services data. But all the services in the same DB will use the same `public` schema.
If service A has newer migrations for the `public` schema and I want to deploy a version of service B that doesn't have the new migrations, if service A is applied first then service B, Service B would complain …
=> Add ability to skip unknown migrations in database

.gitignore, migrate.go
=> fix: oracle database does not support 'if not exists' and 'text' data type

migrate.go
Using `sql-migrate` with Snowflake I got the problem with the execution of the `"SELECT * FROM %s ORDER BY id ASC"`. The quoting of the `ID` column solving the problem.
=> fix: Quote `id` column as it described in dialect definition

README.md
- Fix SQL syntax for `CREATE INDEX CONCURRENTLY`
- Use http**s** links where appropriate
=> Fix README sql and links

migrate.go
The implementation uses the FileSystem of the http package which uses "/" as a separator in paths regardless of the operating system. However, the `filepath.join`-method creates a path using the system-specific separator ("\\" for Windows, see [documentation](https://golang.org/pkg/path/filepath/#Join)) which results in a `http: invalid character in file path`-error in the `migrationFromFile`-method. Using the `path.join`-method instead resolves this issue.
=> Fix Windows filepath separator bug

sql-migrate/command_common.go, sql-migrate/command_redo.go, sql-migrate/command_skip.go, sql-migrate/command_status.go
The database are currently not closed, which may be logged as a failed connection. For example, MySQL logs as follows if `db.Close` was not called:
```
[Note] Aborted connection N to db: 'xxx' user: 'yyy' host: 'zzz' (Got an error reading communication packets)
```
=> Close the database before exiting

go.mod, go.sum, migrate.go
I would love to use sql migrate for handling database schema changes in snowflake db, as we are already using it for some ETL jobs with a PG database.
This adds snowflake support (needed to be added to gorp first, where it was added with the v3.1.0 release)
=> Add snowflake support and upgrade gorp dependency to v3.1.0

README.md
sslmode is set to required in the example of dbconfig.yml in the readme, but sslmode has to be one of "require", "verify-full", "verify-ca", or "disable" (https://github.com/lib/pq/blob/381d253611d666974d43dfa634d29fe16ea9e293/ssl.go#L14).
=> fix: config example sslmode to require, not required

sql-migrate/main.go
Currently `sql-migrate --version` outputs to stderr instead of stdout
I've added HelpWriter and ErrorWriter to cli.CLI
https://github.com/mitchellh/cli/blob/784fcd13e857c49c0e5738a19707762f372a3eb3/cli.go#L119
=> add HelpWriter and ErrorWriter (#2)

sql-migrate/main.go
I would expect error message to go to stderr when returning exit code 1 if migration fails
https://github.com/rubenv/sql-migrate/blob/29b22c8302724a6cf2022a1645bacaa1fd7036fe/sql-migrate/command_up.go#L52
If it's a breaking change or it is intended, you can close this PR
=> Use stderr instead of stdout for ui error writer

.github/workflows/release.yml, .github/workflows/test.yml, .golangci.yaml, go.mod, go.sum, test-integration/mysql-flag.sh
updated golang.org/x/crypto to v0.37.0 due to security reasons
bump go version to 1.23 ( due to versions < 1.23 not supported by go security guides )
bump actions & golangci-lint versions
=> updated golang.org/x/crypto to v0.37.0
